---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livebook-auth
  namespace: livebook
spec:
  encryptedData:
    livebookPassword: AgCPv3pztB1RS/VyRAlp1UkSQR8Kwhxa5WCSVzacijERmlnDhPZcDWRX4asqBYtG9X4TOHmZY9b9uaA9t/++owUL0kii5ce+wM7wB5bPpBFpNGs+AWkhJBZ7sNSfL0R0g7rKxLFtQgsTZYXlz8nWpuOqgN0nPwHKstQWsf6h0jwvYkLo/zREl0LxWwF1bLyieGBcpJeaI9aae4LmbJ7kmlnhjU53OYhEcAI9S4EQhxMpYrgb9aIMs2bGKZCwunvrJQvXfZVaKH0XhtR+jtJvHnJd/zJ8xpTLb82Klv7Kyq3XH/MoqJVN0bF0xGTfnZn9wwotCqJkPaULKl5ImSW5dBkzQgggwM0NcvMbvA7zAr1gZzFLMwbsBF4VVWJmQuk3SeJAt4D6wa02M/IMdozPiFU363Ms0YrFuYv4ADVsG7RH2oBRnN+G1RRMMI/IAqVnZsGovrjx/EL5oTSwQ3F6fZ3ftTidUWqbdzTr8GQ2fH7IkqSN0s0T7AewtNOB3XazR/ipP64HqOwc77DY0N1eiaDJ5qi0MToWlWcH0zfRz/mmY3bGAvM6gLtJOkAp7uqK3ZOXuCvhgYd1FjqUVyzux7OkRJZRmu1T0hbFyss8aLhuZRHi1o8u7sE02H9l7M7HNz7cmXGg5fkAcOApIeHPWH6l5BCCMTcNo4anS9PXQOTK7DdqUd9/4+iDe6KGh8uNZt0P6GjMvjYMSIql0PXqAxm8/H1hwvOTMBnyNydnm9E+A3KVF0Jt3rtRUH4rzQ==
  template:
    metadata:
      name: livebook-auth
      namespace: livebook
