apiVersion: v1
kind: Service
metadata:
  name: {{ include "nerves-hub.fullname" . }}
  labels:
    {{- include "nerves-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nervesHub.service.type }}
  ports:
    - port: {{ .Values.nervesHub.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nerves-hub.selectorLabels" . | nindent 4 }}
